"""Type hints for sqlean package."""

from sqlean import extensions as extensions
from sqlean.dbapi2 import (
    connect as connect,
    Connection as Connection,
    Cursor as Cursor,
    Row as Row,
    Date as Date,
    Time as Time,
    Timestamp as Timestamp,
    DateFromTicks as DateFromTicks,
    TimeFromTicks as TimeFromTicks,
    TimestampFromTicks as TimestampFromTicks,
    Binary as Binary,
    OptimizedUnicode as OptimizedUnicode,
    register_adapter as register_adapter,
    register_converter as register_converter,
    NotSupportedError as NotSupportedError,
    DatabaseError as DatabaseError,
    DataError as DataError,
    OperationalError as OperationalError,
    IntegrityError as IntegrityError,
    InternalError as InternalError,
    ProgrammingError as ProgrammingError,
    Warning as Warning,
    Error as Error,
    InterfaceError as InterfaceError,
    # Constants
    SQLITE_OK as SQLITE_OK,
    SQLITE_DENY as SQLITE_DENY,
    SQLITE_IGNORE as SQLITE_IGNORE,
    SQLITE_CREATE_INDEX as SQLITE_CREATE_INDEX,
    SQLITE_CREATE_TABLE as SQLITE_CREATE_TABLE,
    SQLITE_CREATE_TEMP_INDEX as SQLITE_CREATE_TEMP_INDEX,
    SQLITE_CREATE_TEMP_TABLE as SQLITE_CREATE_TEMP_TABLE,
    SQLITE_CREATE_TEMP_TRIGGER as SQLITE_CREATE_TEMP_TRIGGER,
    SQLITE_CREATE_TEMP_VIEW as SQLITE_CREATE_TEMP_VIEW,
    SQLITE_CREATE_TRIGGER as SQLITE_CREATE_TRIGGER,
    SQLITE_CREATE_VIEW as SQLITE_CREATE_VIEW,
    SQLITE_DELETE as SQLITE_DELETE,
    SQLITE_DROP_INDEX as SQLITE_DROP_INDEX,
    SQLITE_DROP_TABLE as SQLITE_DROP_TABLE,
    SQLITE_DROP_TEMP_INDEX as SQLITE_DROP_TEMP_INDEX,
    SQLITE_DROP_TEMP_TABLE as SQLITE_DROP_TEMP_TABLE,
    SQLITE_DROP_TEMP_TRIGGER as SQLITE_DROP_TEMP_TRIGGER,
    SQLITE_DROP_TEMP_VIEW as SQLITE_DROP_TEMP_VIEW,
    SQLITE_DROP_TRIGGER as SQLITE_DROP_TRIGGER,
    SQLITE_DROP_VIEW as SQLITE_DROP_VIEW,
    SQLITE_INSERT as SQLITE_INSERT,
    SQLITE_PRAGMA as SQLITE_PRAGMA,
    SQLITE_READ as SQLITE_READ,
    SQLITE_SELECT as SQLITE_SELECT,
    SQLITE_TRANSACTION as SQLITE_TRANSACTION,
    SQLITE_UPDATE as SQLITE_UPDATE,
    SQLITE_ATTACH as SQLITE_ATTACH,
    SQLITE_DETACH as SQLITE_DETACH,
    SQLITE_REINDEX as SQLITE_REINDEX,
    SQLITE_ANALYZE as SQLITE_ANALYZE,
    SQLITE_CREATE_VTABLE as SQLITE_CREATE_VTABLE,
    SQLITE_DROP_VTABLE as SQLITE_DROP_VTABLE,
    SQLITE_FUNCTION as SQLITE_FUNCTION,
    SQLITE_SAVEPOINT as SQLITE_SAVEPOINT,
    SQLITE_RECURSIVE as SQLITE_RECURSIVE,
    paramstyle as paramstyle,
    threadsafety as threadsafety,
    apilevel as apilevel,
    version as version,
    sqlite_version as sqlite_version,
    version_info as version_info,
    sqlite_version_info as sqlite_version_info,
)

__all__ = [
    "connect",
    "Connection",
    "Cursor",
    "Row",
    "Date",
    "Time",
    "Timestamp",
    "DateFromTicks",
    "TimeFromTicks",
    "TimestampFromTicks",
    "Binary",
    "OptimizedUnicode",
    "register_adapter",
    "register_converter",
    "extensions",
    "NotSupportedError",
    "DatabaseError",
    "DataError",
    "OperationalError",
    "IntegrityError",
    "InternalError",
    "ProgrammingError",
    "Warning",
    "Error",
    "InterfaceError",
]
